### ISSUE TITLE
Stuck on Module Loading

### ISSUE THREAD

**Issue by BerkSmash1984** [tylerstambaugh/MMM-Strava-Last-Activity-Map#17]
After installing the module and adding the needed info to my MM config, the module is stuck on loading:

![image](https://github.com/tylerstambaugh/MMM-Strava-Last-Activity-Map/assets/104693081/32d602bb-185e-48d9-a115-11208987b9b6)

Any ideas? Not seeing anything stand out in the MM logs, or in the dev console in my browser. I already have a working Strava client ID and client secret that are functional (currently using the MMM-Strava module without issue).  I generated the Strava refresh token via the instructions provided on https://developers.strava.com/docs/getting-started/#oauth and doing the curl request. I also already had a Google Maps API key handy.

Any help would be appreciated. Thanks!

**Comment by tylerstambaugh** [comment]
Hmm... Is there a file named:  "strava_access_token.json" in the modules directory of your MM project? If there is, try deleting it and re-running the project.

**Comment by BerkSmash1984** [comment]
There was indeed a file but removing it and then stopping and restarting the MM via pm2 did not resolve the issue. The file was also regenerated after starting the MM again, but I am assuming this is expected?

**Comment by tylerstambaugh** [comment]
@BerkSmash1984 Yes, that is expected and it is good that it regenerated. My guess is that the access token does not have the required scopes to pull the data from the Strava API. Can you go through the auth process again to get a new token and make sure you have the req'd scopes? I think it is just: activity:read_all, but maybe trying different scopes could help pinpoint the issue. 

Regards,
Tyler

**Comment by BerkSmash1984** [comment]
I will give it another go this AM. Is there anything I should look out for in the dev console or MM logs that may indicate what the issue is?

**Comment by BerkSmash1984** [comment]
@tylerstambaugh it looks like my scope is set to just read, but this seems to work fine for the MMM-Strava module. I am not seeing a way to change the scope though?

![image](https://github.com/tylerstambaugh/MMM-Strava-Last-Activity-Map/assets/104693081/85ebc349-2b07-481b-8cfc-f9399aa8bb16)

Is read_all absolutely required?

**Comment by tylerstambaugh** [comment]
@BerkSmash1984 Yes, I do not believe that scope will work. You'll have to request a new auth/refresh token with the appropriate scope in the request parameters. There may also be an issue using the same token across modules, since the MMM-Strava module may get a refreshed token which would expire the access token for this module. That is why I put the access_token.json file in the folder above both of my modules, so that it can be shared between them since I have both of my modules on my MM. I hope this helps.

**Comment by BerkSmash1984** [comment]
@tylerstambaugh  I went through the whole process again and authorized a scope of read_all:

http://www.strava.com/oauth/authorize?client_id=[MY_CLIENT_ID]&response_type=code&redirect_uri=http://localhost/exchange_token&approval_prompt=force&scope=read_all

![image](https://github.com/tylerstambaugh/MMM-Strava-Last-Activity-Map/assets/104693081/56c5e53f-e9f5-40af-bbd7-d7982ec041a2)


but it appears I have hit my rate limit for the day, which is surprising, as I have the longest update/refresh intervals allowable in the MMM-Strava modules  I am using. 

![image](https://github.com/tylerstambaugh/MMM-Strava-Last-Activity-Map/assets/104693081/160819da-588e-4d3c-8b15-d17941723de3)

Oddly enough, despite the new authorization with the corrected scope and updated refresh and access tokens, provided via curl command, on the Strava API page, it still says the old refresh and access tokens, and just read for scope. Not sure if this is because I hit my limit for the day or what. I will have to keep playing with it

**Comment by BerkSmash1984** [comment]
@tylerstambaugh I was not able to work past the issue despite the attempts made yesterday. The module actually causes me to reach the API limit, at least when attempting to use with in conjunction with MMM-Strava. You can see that on the 25th and 26th, I reached my daily API request limit of 1000 per day, and then when troubleshooting this AM, my API request within a 15 min period quickly jumped to over the 100 requests per 15 min limit, causing me to exceed the 15 min allowable amount and resulting in 429 "Rate Limit Exceeded" errors

![image](https://github.com/tylerstambaugh/MMM-Strava-Last-Activity-Map/assets/104693081/aa59d310-6867-4968-8f48-7b81c305194a)

I am going to be removing the module for now. Perhaps as a future enhancement request, your module could leverage what is used for MMM-Strava for authentication/authorization to prevent the spikes in API requests. I appreciate all your responses in helping me to troubleshoot.

**Comment by BerkSmash1984** [comment]
Closing per my last comment above

**Comment by tylerstambaugh** [comment]
@BerkSmash1984  I'll take a look into limiting the requests when not receiving a success. Thanks for the feedback.
